GET http://localhost:3001/user/663fc17e8a9d5fe8d1c0f84a

###

POST http://localhost:3001/contactUs/new
Content-Type: application/json

{
    "user": "teste",
    "mensagem": "teste"
}

###

POST http://localhost:3001/userLogIn
Content-Type: application/json

{
    "email": "Santana",
    "password": "Santana"

}

###

GET http://localhost:3001/download/imagem_teste.jpg
Content-Type: application/json

{
  "id": 1,
  "name": "imagem_teste",
  "description": "Este é um exemplo de objeto JSON para testar o servidor com uma imagem.",
  "image_url": "/download/imagem_teste.jpg"
}